DROP TABLE [Announcements];
DROP TABLE [UserAnnouncements];
DROP TABLE [Brackets];
DROP TABLE [Tournaments];
DROP TABLE [Friends];
DROP TABLE [ReceivedFriendRequests];
DROP TABLE [SentFriendRequests];
DROP TABLE [BitUser];
DROP TABLE [__EFMigrationsHistory];